### ISSUE TITLE
Realtime kernel not available

### ISSUE THREAD

**Issue by ylebars** [ycollet/fedora-spec#10]
I have just installed a new computer, to run Fedora 31, enabled this COPR repository and installed the realtime kernel:

$ rpm -qa | grep kernel-rt-mao
kernel-rt-mao-5.2.21.rt15-9.fc31.x86_64
kernel-rt-mao-5.2.21.rt14-9.fc31.x86_64

However, I cannot see any realtime kernel on GRUB’s boot menu. Is this
a known issue?

**Comment by ycollet** [comment]
I just installed a RT kernel on Fedora 31 and during installation, I've seen this message:

```
La vérification de la transaction a réussi.
Lancement de la transaction de test
Transaction de test réussie.
Exécution de la transaction
  Préparation           :                                                                                                                                                                                                                1/1 
  Installation          : kernel-rt-mao-5.2.21.rt15-9.fc31.x86_64                                                                                                                                                                        1/1 
  Exécution du scriptlet: kernel-rt-mao-5.2.21.rt15-9.fc31.x86_64                                                                                                                                                                        1/1 
Kernel image argument /lib/modules/5.2.21-rt15.fc31.x86_64/vmlinuz not a file
Generating grub configuration file ...
done
```
So, a copy of vmlinuz is missing here.
This was not generating any errors on 29 and 30 so, maybe something has changed on Fedora 31.
I will fix this ASAP.

Thanks for the report.

----- Mail original -----
De: "Yoann Le Bars" <notifications@github.com>
À: "ycollet/fedora-spec" <fedora-spec@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Envoyé: Mardi 17 Décembre 2019 14:19:03
Objet: [ycollet/fedora-spec] Realtime kernel not available (#10)



I have just installed a new computer, to run Fedora 31, enabled this COPR repository and installed the realtime kernel: 

$ rpm -qa | grep kernel-rt-mao 
kernel-rt-mao-5.2.21.rt15-9.fc31.x86_64 
kernel-rt-mao-5.2.21.rt14-9.fc31.x86_64 

However, I cannot see any realtime kernel on GRUB’s boot menu. Is this 
a known issue? 

— 
You are receiving this because you are subscribed to this thread. 
Reply to this email directly, view it on GitHub , or unsubscribe .

**Comment by ycollet** [comment]
I tested this firt:
```
cd /boot
cp vmlinuz-5.2.21-rt15.fc31.x86_64 /lib/modules/5.2.21-rt15.fc31.x86_64/vmlinuz
grub2-mkconfig -o /boot/grub2/grub.cfg
```
And it doesn't work.
Then:
```
chmod a+x /lib/modules/5.2.21-rt15.fc31.x86_64/vmlinuz
```
And this works.
So, for a quick fix: copy vmlinuz and the chmod a+x ...

**Comment by ylebars** [comment]
I have tried the workaround, but the kernel is still not available in
GRUB boot menu.

-- 
Yoann LE BARS
http://le-bars.net/yoann/
Diaspora* : ylebars@framasphere.org

**Comment by ycollet** [comment]
My fault: a step was missing.
The complete workaround:
```
cd /boot
cp vmlinuz-5.2.21-rt15.fc31.x86_64 /lib/modules/5.2.21-rt15.fc31.x86_64/vmlinuz
chmod a+x /lib/modules/5.2.21-rt15.fc31.x86_64/vmlinuz
grub2-mkconfig -o /boot/grub2/grub.cfg
```
So, just do a:
```
grub2-mkconfig -o /boot/grub2/grub.cfg
```
To finish the last step

**Comment by ycollet** [comment]
A new build is running on COPR server.
I built it locally on fedora 30 and tested it on Fedora 31 and this kernel is correctly detected by grub.
Link to the build:
https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/build/1130993/
