### ISSUE TITLE
Surge, Odin and Vitalium VST3 are not listed by Ardour 6.6 in Fedora 34.

### ISSUE THREAD

**Issue by tonilink** [ycollet/fedora-spec#24]
I installed these 3 VST3 synths in a fresh new Fedora 34, from linuxmao repo, and Ardour from the official build. But Ardour can't open nor list theses plugins.

**Comment by ycollet** [comment]
Normaly, Surge works fine. Surge comes as a LV2 and VST3.
Odin does not work really nicely. I was able to make it works in Carla but once added in Carla in LMMS , Odin hangs.
And Vitalium, worked fine with Carla and Carla + LMMS. 
I never tried Ardour but I think there is something like Carla: you need to scan the vst before using them. And maybe the problem (like in Carla) is that the VST / VST3 / LV2 directories are not set correctly: /usr/lib/lv2 instead of /usr/lib64/lv2 and /usr/lib/vst{3} instead of /usr/lib64/vst{3}.
Can you check that ? (the plugin directories) and then start a new scan.

**Comment by tonilink** [comment]
I don't know if it is the correct way to do that, but I just copied the *.vst folders from /usr/lib64/vst3/ to my local .vst3/ and they are working fine.

**Comment by ycollet** [comment]
So, it's certainly a wrong setting in the plugin paths in Ardour.
If the copy works for you let's say it's a solution :)
I will try to have a look at the ardour preferences dialog.

**Comment by ycollet** [comment]
https://manual.ardour.org/preferences-and-session-properties/preferences-dialog/#preferences-plugins
